apiVersion: v1
kind: Secret
metadata:
  name: auditoria-service-secret
  namespace: unifiapay # Importante: pertence ao mesmo namespace
type: Opaque # Tipo padrão para dados de chave-valor
data:
  # A chave é 'FAKE_PIX_KEY' e o valor está em Base64
  FAKE_PIX_KEY: TVRJeE5EVTJOemc1TUZBaFljRGVmZw==