apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: unifiapay-role
  namespace: unifiapay
rules:
- apiGroups: [""] # API Core
  resources:
  - pods
  - jobs # Necessário para o CronJob
  verbs:
  - get
  - list
  - watch
- apiGroups: [""] # API Core
  resources:
  - configmaps
  - secrets
  verbs:
  - get # Permissão mínima, apenas 'get' e não 'list' ou 'watch'